// Autogenerated from Pigeon (v29.0.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class HostAPIError: Error {
  let code: String
  let message: String?
  let details: Sendable?

  init(code: String, message: String?, details: Sendable?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "HostAPIError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>"))"
  }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? HostAPIError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(Swift.type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func createConnectionError(withChannelName channelName: String) -> HostAPIError {
  return HostAPIError(code: "channel-error", message: "Unable to establish connection on channel: '\(channelName)'.", details: "")
}

enum HostAPIPigeonInternal {
  static func isNullish(_ value: Any?) -> Bool {
    guard let innerValue = value else {
      return true
    }

    if case Optional<Any>.some(Optional<Any>.none) = value {
      return true
    }

    return innerValue is NSNull
  }
  static func doubleEquals(_ lhs: Double, _ rhs: Double) -> Bool {
    return (lhs.isNaN && rhs.isNaN) || lhs == rhs
  }

  static func doubleHash(_ value: Double, _ hasher: inout Hasher) {
    if value.isNaN {
      hasher.combine(0x7FF8000000000000)
    } else {
      // Normalize -0.0 to 0.0
      hasher.combine(value == 0 ? 0 : value)
    }
  }

  static func deepEquals(_ lhs: Any?, _ rhs: Any?) -> Bool {
    let cleanLhs = nilOrValue(lhs) as Any?
    let cleanRhs = nilOrValue(rhs) as Any?
    switch (cleanLhs, cleanRhs) {
    case (nil, nil):
      return true

    case (nil, _), (_, nil):
      return false

    case (let lhs as AnyObject, let rhs as AnyObject) where lhs === rhs:
      return true

    case is (Void, Void):
      return true

    case (let lhsArray, let rhsArray) as ([Double], [Double]):
      guard lhsArray.count == rhsArray.count else { return false }
      for (index, element) in lhsArray.enumerated() {
        if !doubleEquals(element, rhsArray[index]) {
          return false
        }
      }
      return true

    case (let lhsArray, let rhsArray) as ([Any?], [Any?]):
      guard lhsArray.count == rhsArray.count else { return false }
      for (index, element) in lhsArray.enumerated() {
        if !deepEquals(element, rhsArray[index]) {
          return false
        }
      }
      return true

    case (let lhsDictionary, let rhsDictionary) as ([AnyHashable: Any?], [AnyHashable: Any?]):
      guard lhsDictionary.count == rhsDictionary.count else { return false }
      for (lhsKey, lhsValue) in lhsDictionary {
        var found = false
        for (rhsKey, rhsValue) in rhsDictionary {
          if deepEquals(lhsKey, rhsKey) {
            if deepEquals(lhsValue, rhsValue) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if !found { return false }
      }
      return true

    case (let lhs as Double, let rhs as Double):
      return doubleEquals(lhs, rhs)

    case (let lhsHashable, let rhsHashable) as (AnyHashable, AnyHashable):
      return lhsHashable == rhsHashable

    default:
      return false
    }
  }

  static func deepHash(value: Any?, hasher: inout Hasher) {
    let cleanValue = nilOrValue(value) as Any?
    if let cleanValue = cleanValue {
      if let doubleValue = cleanValue as? Double {
        doubleHash(doubleValue, &hasher)
      } else if let valueList = cleanValue as? [Any?] {
        for item in valueList {
          deepHash(value: item, hasher: &hasher)
        }
      } else if let valueList = cleanValue as? [Double] {
        for item in valueList {
          doubleHash(item, &hasher)
        }
      } else if let valueDict = cleanValue as? [AnyHashable: Any?] {
        var result = 0
        for (key, value) in valueDict {
          var entryKeyHasher = Hasher()
          deepHash(value: key, hasher: &entryKeyHasher)
          var entryValueHasher = Hasher()
          deepHash(value: value, hasher: &entryValueHasher)
          result = result &+ ((entryKeyHasher.finalize() &* 31) ^ entryValueHasher.finalize())
        }
        hasher.combine(result)
      } else if let hashableValue = cleanValue as? AnyHashable {
        hasher.combine(hashableValue)
      } else {
        hasher.combine(String(describing: cleanValue))
      }
    } else {
      hasher.combine(0)
    }
  }

}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}


/// 画面収録の許可。許可の仕組みを持たない OS は常に `granted`
enum ScreenPermission: Int, CaseIterable {
  case granted = 0
  /// まだ尋ねていない。尋ねればダイアログが出る
  case notRequested = 1
  /// 一度尋ねている。以後はシステム設定で許可してもらうしかない
  case requestedBefore = 2
}

enum ServerStatus: Int, CaseIterable {
  case idle = 0
  case starting = 1
  case running = 2
  case failed = 3
}

enum StreamStatus: Int, CaseIterable {
  case idle = 0
  case awaitingApproval = 1
  case starting = 2
  case streaming = 3
  case failed = 4
}

/// ビューアが選んだ画質（SPEC.md §7.2）
enum StreamQuality: Int, CaseIterable {
  case sharp = 0
  case balanced = 1
  case smooth = 2
}

/// ビューアに渡す接続先。画面ごと・インタフェースごとに 1 件（SPEC.md §5.2）
///
/// Generated class from Pigeon that represents data sent in messages.
struct EndpointState: Hashable, CustomStringConvertible {
  var interfaceName: String
  /// 既定は HTTP（SPEC.md §5.3）
  var url: String
  /// 証明書を用意できなかったときは null
  var secureUrl: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> EndpointState? {
    let interfaceName = pigeonVar_list[0] as! String
    let url = pigeonVar_list[1] as! String
    let secureUrl: String? = nilOrValue(pigeonVar_list[2])

    return EndpointState(
      interfaceName: interfaceName,
      url: url,
      secureUrl: secureUrl
    )
  }
  func toList() -> [Any?] {
    return [
      interfaceName,
      url,
      secureUrl,
    ]
  }
  static func == (lhs: EndpointState, rhs: EndpointState) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return HostAPIPigeonInternal.deepEquals(lhs.interfaceName, rhs.interfaceName) && HostAPIPigeonInternal.deepEquals(lhs.url, rhs.url) && HostAPIPigeonInternal.deepEquals(lhs.secureUrl, rhs.secureUrl)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("EndpointState")
    HostAPIPigeonInternal.deepHash(value: interfaceName, hasher: &hasher)
    HostAPIPigeonInternal.deepHash(value: url, hasher: &hasher)
    HostAPIPigeonInternal.deepHash(value: secureUrl, hasher: &hasher)
  }

  public var description: String {
    return "EndpointState(interfaceName: \(String(describing: interfaceName)), url: \(String(describing: url)), secureUrl: \(String(describing: secureUrl)))"
  }
}

/// 画面 1 枚ぶんの配信
///
/// Generated class from Pigeon that represents data sent in messages.
struct DisplayStreamState: Hashable, CustomStringConvertible {
  var displayId: Int64
  var name: String
  var pixelWidth: Int64
  var pixelHeight: Int64
  var status: StreamStatus
  /// 承認待ち・接続中・配信中のビューアのアドレス
  var peerAddress: String? = nil
  /// `failed` の理由。コアが表示言語で組み立てた文言
  var failure: String? = nil
  /// ビューアの表示サイズへ追従した実効解像度（SPEC.md §7.1）。配信中だけ
  var activeWidth: Int64? = nil
  var activeHeight: Int64? = nil
  var quality: StreamQuality
  var endpoints: [EndpointState]


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> DisplayStreamState? {
    let displayId = pigeonVar_list[0] as! Int64
    let name = pigeonVar_list[1] as! String
    let pixelWidth = pigeonVar_list[2] as! Int64
    let pixelHeight = pigeonVar_list[3] as! Int64
    let status = pigeonVar_list[4] as! StreamStatus
    let peerAddress: String? = nilOrValue(pigeonVar_list[5])
    let failure: String? = nilOrValue(pigeonVar_list[6])
    let activeWidth: Int64? = nilOrValue(pigeonVar_list[7])
    let activeHeight: Int64? = nilOrValue(pigeonVar_list[8])
    let quality = pigeonVar_list[9] as! StreamQuality
    let endpoints = pigeonVar_list[10] as! [EndpointState]

    return DisplayStreamState(
      displayId: displayId,
      name: name,
      pixelWidth: pixelWidth,
      pixelHeight: pixelHeight,
      status: status,
      peerAddress: peerAddress,
      failure: failure,
      activeWidth: activeWidth,
      activeHeight: activeHeight,
      quality: quality,
      endpoints: endpoints
    )
  }
  func toList() -> [Any?] {
    return [
      displayId,
      name,
      pixelWidth,
      pixelHeight,
      status,
      peerAddress,
      failure,
      activeWidth,
      activeHeight,
      quality,
      endpoints,
    ]
  }
  static func == (lhs: DisplayStreamState, rhs: DisplayStreamState) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return HostAPIPigeonInternal.deepEquals(lhs.displayId, rhs.displayId) && HostAPIPigeonInternal.deepEquals(lhs.name, rhs.name) && HostAPIPigeonInternal.deepEquals(lhs.pixelWidth, rhs.pixelWidth) && HostAPIPigeonInternal.deepEquals(lhs.pixelHeight, rhs.pixelHeight) && HostAPIPigeonInternal.deepEquals(lhs.status, rhs.status) && HostAPIPigeonInternal.deepEquals(lhs.peerAddress, rhs.peerAddress) && HostAPIPigeonInternal.deepEquals(lhs.failure, rhs.failure) && HostAPIPigeonInternal.deepEquals(lhs.activeWidth, rhs.activeWidth) && HostAPIPigeonInternal.deepEquals(lhs.activeHeight, rhs.activeHeight) && HostAPIPigeonInternal.deepEquals(lhs.quality, rhs.quality) && HostAPIPigeonInternal.deepEquals(lhs.endpoints, rhs.endpoints)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("DisplayStreamState")
    HostAPIPigeonInternal.deepHash(value: displayId, hasher: &hasher)
    HostAPIPigeonInternal.deepHash(value: name, hasher: &hasher)
    HostAPIPigeonInternal.deepHash(value: pixelWidth, hasher: &hasher)
    HostAPIPigeonInternal.deepHash(value: pixelHeight, hasher: &hasher)
    HostAPIPigeonInternal.deepHash(value: status, hasher: &hasher)
    HostAPIPigeonInternal.deepHash(value: peerAddress, hasher: &hasher)
    HostAPIPigeonInternal.deepHash(value: failure, hasher: &hasher)
    HostAPIPigeonInternal.deepHash(value: activeWidth, hasher: &hasher)
    HostAPIPigeonInternal.deepHash(value: activeHeight, hasher: &hasher)
    HostAPIPigeonInternal.deepHash(value: quality, hasher: &hasher)
    HostAPIPigeonInternal.deepHash(value: endpoints, hasher: &hasher)
  }

  public var description: String {
    return "DisplayStreamState(displayId: \(String(describing: displayId)), name: \(String(describing: name)), pixelWidth: \(String(describing: pixelWidth)), pixelHeight: \(String(describing: pixelHeight)), status: \(String(describing: status)), peerAddress: \(String(describing: peerAddress)), failure: \(String(describing: failure)), activeWidth: \(String(describing: activeWidth)), activeHeight: \(String(describing: activeHeight)), quality: \(String(describing: quality)), endpoints: \(String(describing: endpoints)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct HostState: Hashable, CustomStringConvertible {
  var permission: ScreenPermission
  var server: ServerStatus
  /// `failed` の理由
  var serverFailure: String? = nil
  /// 接続トークン（SPEC.md §5.2）。全画面で共通
  var token: String
  var tokenRemainingSeconds: Int64
  /// 直近の作り直しが「誤りが続いたから」だったか
  var tokenRegeneratedAfterFailures: Bool
  /// 証明書を用意できず HTTP だけで動いているときの理由
  var certificateError: String? = nil
  /// ディスプレイの並び順どおり
  var streams: [DisplayStreamState]


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> HostState? {
    let permission = pigeonVar_list[0] as! ScreenPermission
    let server = pigeonVar_list[1] as! ServerStatus
    let serverFailure: String? = nilOrValue(pigeonVar_list[2])
    let token = pigeonVar_list[3] as! String
    let tokenRemainingSeconds = pigeonVar_list[4] as! Int64
    let tokenRegeneratedAfterFailures = pigeonVar_list[5] as! Bool
    let certificateError: String? = nilOrValue(pigeonVar_list[6])
    let streams = pigeonVar_list[7] as! [DisplayStreamState]

    return HostState(
      permission: permission,
      server: server,
      serverFailure: serverFailure,
      token: token,
      tokenRemainingSeconds: tokenRemainingSeconds,
      tokenRegeneratedAfterFailures: tokenRegeneratedAfterFailures,
      certificateError: certificateError,
      streams: streams
    )
  }
  func toList() -> [Any?] {
    return [
      permission,
      server,
      serverFailure,
      token,
      tokenRemainingSeconds,
      tokenRegeneratedAfterFailures,
      certificateError,
      streams,
    ]
  }
  static func == (lhs: HostState, rhs: HostState) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return HostAPIPigeonInternal.deepEquals(lhs.permission, rhs.permission) && HostAPIPigeonInternal.deepEquals(lhs.server, rhs.server) && HostAPIPigeonInternal.deepEquals(lhs.serverFailure, rhs.serverFailure) && HostAPIPigeonInternal.deepEquals(lhs.token, rhs.token) && HostAPIPigeonInternal.deepEquals(lhs.tokenRemainingSeconds, rhs.tokenRemainingSeconds) && HostAPIPigeonInternal.deepEquals(lhs.tokenRegeneratedAfterFailures, rhs.tokenRegeneratedAfterFailures) && HostAPIPigeonInternal.deepEquals(lhs.certificateError, rhs.certificateError) && HostAPIPigeonInternal.deepEquals(lhs.streams, rhs.streams)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("HostState")
    HostAPIPigeonInternal.deepHash(value: permission, hasher: &hasher)
    HostAPIPigeonInternal.deepHash(value: server, hasher: &hasher)
    HostAPIPigeonInternal.deepHash(value: serverFailure, hasher: &hasher)
    HostAPIPigeonInternal.deepHash(value: token, hasher: &hasher)
    HostAPIPigeonInternal.deepHash(value: tokenRemainingSeconds, hasher: &hasher)
    HostAPIPigeonInternal.deepHash(value: tokenRegeneratedAfterFailures, hasher: &hasher)
    HostAPIPigeonInternal.deepHash(value: certificateError, hasher: &hasher)
    HostAPIPigeonInternal.deepHash(value: streams, hasher: &hasher)
  }

  public var description: String {
    return "HostState(permission: \(String(describing: permission)), server: \(String(describing: server)), serverFailure: \(String(describing: serverFailure)), token: \(String(describing: token)), tokenRemainingSeconds: \(String(describing: tokenRemainingSeconds)), tokenRegeneratedAfterFailures: \(String(describing: tokenRegeneratedAfterFailures)), certificateError: \(String(describing: certificateError)), streams: \(String(describing: streams)))"
  }
}

private class HostAPIPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return ScreenPermission(rawValue: enumResultAsInt)
      }
      return nil
    case 130:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return ServerStatus(rawValue: enumResultAsInt)
      }
      return nil
    case 131:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return StreamStatus(rawValue: enumResultAsInt)
      }
      return nil
    case 132:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return StreamQuality(rawValue: enumResultAsInt)
      }
      return nil
    case 133:
      return EndpointState.fromList(self.readValue() as! [Any?])
    case 134:
      return DisplayStreamState.fromList(self.readValue() as! [Any?])
    case 135:
      return HostState.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class HostAPIPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? ScreenPermission {
      super.writeByte(129)
      super.writeValue(value.rawValue)
    } else if let value = value as? ServerStatus {
      super.writeByte(130)
      super.writeValue(value.rawValue)
    } else if let value = value as? StreamStatus {
      super.writeByte(131)
      super.writeValue(value.rawValue)
    } else if let value = value as? StreamQuality {
      super.writeByte(132)
      super.writeValue(value.rawValue)
    } else if let value = value as? EndpointState {
      super.writeByte(133)
      super.writeValue(value.toList())
    } else if let value = value as? DisplayStreamState {
      super.writeByte(134)
      super.writeValue(value.toList())
    } else if let value = value as? HostState {
      super.writeByte(135)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class HostAPIPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return HostAPIPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return HostAPIPigeonCodecWriter(data: data)
  }
}

class HostAPIPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = HostAPIPigeonCodec(readerWriter: HostAPIPigeonCodecReaderWriter())
}

/// UI → コア
///
/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol HostUIControl {
  /// 起動直後に 1 回だけ取りに行く。以後は `HostUIEvents.stateChanged` が届く
  func currentState() throws -> HostState
  func startServing() throws
  func stopServing() throws
  func regenerateToken() throws
  /// **承認するまでその画面のキャプチャは始まらない**（SPEC.md §5.2）
  func approve(displayId: Int64) throws
  func reject(displayId: Int64) throws
  func disconnect(displayId: Int64) throws
  /// 画面収録の許可を求める。許可の仕組みを持たない OS では何もしない
  func requestPermission() throws
  func openPermissionSettings() throws
  /// 許可を反映するための再起動
  func relaunch() throws
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class HostUIControlSetup {
  static var codec: FlutterStandardMessageCodec { HostAPIPigeonCodec.shared }
  /// Sets up an instance of `HostUIControl` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: HostUIControl?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    /// 起動直後に 1 回だけ取りに行く。以後は `HostUIEvents.stateChanged` が届く
    let currentStateChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.host_ui.HostUIControl.currentState\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      currentStateChannel.setMessageHandler { _, reply in
        do {
          let result = try api.currentState()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      currentStateChannel.setMessageHandler(nil)
    }
    let startServingChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.host_ui.HostUIControl.startServing\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      startServingChannel.setMessageHandler { _, reply in
        do {
          try api.startServing()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      startServingChannel.setMessageHandler(nil)
    }
    let stopServingChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.host_ui.HostUIControl.stopServing\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      stopServingChannel.setMessageHandler { _, reply in
        do {
          try api.stopServing()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      stopServingChannel.setMessageHandler(nil)
    }
    let regenerateTokenChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.host_ui.HostUIControl.regenerateToken\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      regenerateTokenChannel.setMessageHandler { _, reply in
        do {
          try api.regenerateToken()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      regenerateTokenChannel.setMessageHandler(nil)
    }
    /// **承認するまでその画面のキャプチャは始まらない**（SPEC.md §5.2）
    let approveChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.host_ui.HostUIControl.approve\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      approveChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let displayIdArg = args[0] as! Int64
        do {
          try api.approve(displayId: displayIdArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      approveChannel.setMessageHandler(nil)
    }
    let rejectChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.host_ui.HostUIControl.reject\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      rejectChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let displayIdArg = args[0] as! Int64
        do {
          try api.reject(displayId: displayIdArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      rejectChannel.setMessageHandler(nil)
    }
    let disconnectChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.host_ui.HostUIControl.disconnect\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      disconnectChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let displayIdArg = args[0] as! Int64
        do {
          try api.disconnect(displayId: displayIdArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      disconnectChannel.setMessageHandler(nil)
    }
    /// 画面収録の許可を求める。許可の仕組みを持たない OS では何もしない
    let requestPermissionChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.host_ui.HostUIControl.requestPermission\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      requestPermissionChannel.setMessageHandler { _, reply in
        do {
          try api.requestPermission()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      requestPermissionChannel.setMessageHandler(nil)
    }
    let openPermissionSettingsChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.host_ui.HostUIControl.openPermissionSettings\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      openPermissionSettingsChannel.setMessageHandler { _, reply in
        do {
          try api.openPermissionSettings()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      openPermissionSettingsChannel.setMessageHandler(nil)
    }
    /// 許可を反映するための再起動
    let relaunchChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.host_ui.HostUIControl.relaunch\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      relaunchChannel.setMessageHandler { _, reply in
        do {
          try api.relaunch()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      relaunchChannel.setMessageHandler(nil)
    }
  }
}

/// コア → UI
///
/// Generated protocol from Pigeon that represents Flutter messages that can be called from Swift.
protocol HostUIEventsProtocol {
  @MainActor func stateChanged(state stateArg: HostState) async throws
}
class HostUIEvents: HostUIEventsProtocol {
  private let binaryMessenger: FlutterBinaryMessenger
  private let messageChannelSuffix: String
  init(binaryMessenger: FlutterBinaryMessenger, messageChannelSuffix: String = "") {
    self.binaryMessenger = binaryMessenger
    self.messageChannelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
  }
  var codec: HostAPIPigeonCodec {
    return HostAPIPigeonCodec.shared
  }
  @MainActor func stateChanged(state stateArg: HostState) async throws {
    return try await withCheckedThrowingContinuation { continuation in
      let channelName: String = "dev.flutter.pigeon.host_ui.HostUIEvents.stateChanged\(messageChannelSuffix)"
      let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
      channel.sendMessage([stateArg] as [Any?]) { response in
        guard let listResponse = response as? [Any?] else {
          continuation.resume(throwing: createConnectionError(withChannelName: channelName))
          return
        }
        if listResponse.count > 1 {
          let code: String = listResponse[0] as! String
          let message: String? = nilOrValue(listResponse[1])
          let details: String? = nilOrValue(listResponse[2])
          continuation.resume(throwing: HostAPIError(code: code, message: message, details: details))
        } else {
          continuation.resume()
        }
      }
    }
  }
}
