function quote(value) {
  return JSON.stringify(value)
    .replaceAll("\\u2028", "\\u2028")
    .replaceAll("\\u2029", "\\u2029");
}

function identifier(key) {
  return key.replace(/[^A-Za-z0-9_]/g, "_");
}

export function renderCppCatalog(catalog) {
  const rows = catalog.entries.map((entry) => {
    const values = catalog.languages
      .map((language) => `      L${quote(entry.values[language])}`)
      .join(",\n");
    return `  inline constexpr std::array<std::wstring_view, ${catalog.languages.length}> ${identifier(entry.key)}{\n${values}\n  };`;
  });

  return `// Generated by tools/i18n/generate.mjs. Do not edit.
#pragma once

#include <array>
#include <string_view>

namespace doppelscreen::l10n {
  inline constexpr std::array<std::wstring_view, ${catalog.languages.length}> languages{
${catalog.languages.map((language) => `      L${quote(language)}`).join(",\n")}
  };

${rows.join("\n\n")}
}
`;
}
